---
collections:
  - name: microsoft.ad
    version: ">=1.0.0"
  - name: ansible.windows
    version: ">=2.0.0"
  - name: community.docker
    version: ">=3.0.0"
  - name: community.crypto
    version: ">=2.0.0"